baseURL = "https://macj.dev/"
languageCode = "en-us"
title = "Mac Justice"
theme = "minimal"
publishdir = "."


[params]
    author = "Mac Justice"
    description = "Tired of all this nerd shit"
    githubUsername = "macjustice"
    accent = "DarkOliveGreen"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "python", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.icon]]
    url = "mailto:mac.justice@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/macjustice/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/macjustice/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/macjustice/"
    name = "linkedin"
    weight = 4
